### ISSUE TITLE
need help to install fmod godot4 integration.

### ISSUE THREAD

**Issue by smallebrug** [jordigcs/fmod_gd4#3]
Followed your Setup guide (readme.md) and it seem to work... I am lost after compiling Godot (I think) The first sign that something is not correct is  ...Configure FMOD by visting Project Settings/Fmod.   I don't have FMOD under Project settings. What could have been gone wrong?

**Comment by jordigulley** [comment]
Sorry for the late response.
Make sure `Advanced Settings` is enabled in Project Settings. In the next release, the FMOD Config won't require this.
![image](https://user-images.githubusercontent.com/12436824/221335309-69cea879-03bd-4501-abac-05c50ba7d3b6.png)
