### ISSUE TITLE
Can't enable debugging

### ISSUE THREAD

**Issue by cramonns** [jordigcs/fmod_gd4#8]
I was able to build the engine with the fmod module, however i can't debug. I always get the message "Unable to enable debugging. Must be using the logging release of FMOD.", but i couldn't find anything about a "logging release" of FMOD. Am I doing something wrong?

![image](https://github.com/jordigcs/fmod_gd4/assets/11017526/603cf027-28ce-4001-bb52-9029dbbb7333)

**Comment by jordigulley** [comment]
The logging release is gonna be the FMOD lib that ends with a capital L, such as `fmodL.dll` Hope this helps!

**Comment by cramonns** [comment]
It worked. Thank you!
